version: 0.2
phases:
  install:
    commands:
      - echo "Start The Build"
      - cd app
      - pip install -r requirements.txt -t .
      - cd ..
      - aws cloudformation package --template-file template.yaml --s3-bucket my-new-bucket-fullofpotato  --output-template-file packaged.yaml
artifacts:
  files:
    - template.yaml
    - packaged.yaml
